enum ERROR_CODES {
  NOT_FOUND = 404,
  ACCESS_TOKEN_INVALID = 401,
  SIGNATURE_INVALID = 400,
  INTERNAL_SERVER_ERROR = 500,
  USERNAME_NOT_AVAILABLE = 409,
  INVALID_USERNAME = 400,
}

export { ERROR_CODES };
